# Generated by Django 5.1.1 on 2025-08-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeaide",
            name="statut",
            field=models.CharField(
                choices=[
                    ("soumise", "En attente"),
                    ("validee", "Validée"),
                    ("refusee", "Refusée"),
                ],
                default="soumise",
                max_length=20,
            ),
        ),
    ]
