# Generated by Django 5.1.1 on 2025-08-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0002_alter_demandeaide_statut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="famille",
            name="type_famille",
        ),
    ]
