# Generated by Django 5.1.1 on 2025-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0003_remove_famille_type_famille"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichevictime",
            name="matricule",
            field=models.CharField(blank=True, max_length=50, verbose_name="Matricule"),
        ),
    ]
