# Generated by Django 5.1.1 on 2025-10-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0004_fichevictime_matricule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichevictime",
            name="matricule",
        ),
    ]
