# Generated by Django 5.1.1 on 2025-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0006_add_matricule_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichevictime",
            name="matricule",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Matricule"
            ),
        ),
    ]
