# Generated by Django 5.1.1 on 2025-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0007_alter_fichevictime_matricule"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichevictime",
            name="statut_victime",
            field=models.CharField(
                choices=[("decede", "Décédé"), ("blesse", "Blessé")],
                default="decede",
                max_length=20,
                verbose_name="Statut de la victime",
            ),
        ),
        migrations.AlterField(
            model_name="fichevictime",
            name="matricule",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="INCO"
            ),
        ),
    ]
