# Generated by Django 5.1.1 on 2025-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0008_fichevictime_statut_victime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichevictime",
            name="matricule",
            field=models.CharField(max_length=50, unique=True, verbose_name="INCO"),
        ),
    ]
