# Generated by Django 5.1.1 on 2025-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0009_alter_fichevictime_matricule"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichevictime",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos_victimes/",
                verbose_name="Photo",
            ),
        ),
    ]
