# Generated by Django 5.1.1 on 2025-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0010_fichevictime_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="membrefamille",
            name="ville",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
    ]
