# Generated by Django 5.1.1 on 2025-12-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victimes", "0011_membrefamille_ville"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVictime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("acte_deces", "Acte de décès"),
                            ("rapport_medical", "Rapport médical"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents_victimes/", verbose_name="Fichier"
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom du fichier"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "victime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="victimes.fichevictime",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document victime",
                "verbose_name_plural": "Documents victimes",
            },
        ),
    ]
