"""
Django settings for gendarmerie project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c11oewtjh)a#5k4ps7z1y=+($#c4sz37s#uo!2xgz%90pay%*2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "victimes",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "gendarmerie.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gendarmerie.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "gendarmerie_db",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "3306",
        # Remplacez les valeurs ci-dessus par vos vrais identifiants MySQL
    }
}

#configuration base de données sqlite (pour tests uniquement)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr"
TIME_ZONE = "Africa/Ouagadougou"
USE_I18N = True
USE_TZ = True
# Jazzmin settings pour interface en français
JAZZMIN_SETTINGS = {
    "site_title": "Administration Gendarmerie",
    "site_header": "Gendarmerie - Administration",
    "site_brand": "Gendarmerie",
    "welcome_sign": "Bienvenue dans l'administration de la Gendarmerie",
    "copyright": "Gendarmerie Nationale",
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "language_chooser": True,
    "site_logo": "images/OIP.webp",  # Placez OIP.webp dans static/images/
    "site_logo_classes": "",  # logo sur login seulement
    "site_brand": "Gendarmerie",
    "site_icon": None,
    "topmenu_links": [
        {"name": "Accueil", "url": "/admin/", "permissions": ["auth.view_user"]},
        {"model": "victimes.user"},
        {"app": "victimes"},
    ],
    "usermenu_links": [
        {"name": "Site public", "url": "/", "new_window": True},
    ],
    "show_ui_builder": False,
    "order_with_respect_to": ["victimes", "auth", "admin"],
    "custom_css": "static/admin/custom_admin.css",  # Ajoutez un fichier CSS personnalisé si besoin
    "custom_js": None,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"victimes.user": "collapsible"},
    "related_modal_active": True,
    "navigation_expanded": True,
    "search_model": "victimes.User",
    "show_sidebar": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "victimes.user": "fas fa-user-shield",
        "victimes.famille": "fas fa-users",
        "victimes.membrefamille": "fas fa-user-friends",
        "victimes.fichevictime": "fas fa-id-card-alt",
        "victimes.demandeaide": "fas fa-hands-helping",
        "victimes.journalaction": "fas fa-history",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_ui_builder": False,
    "custom_links": {
        "victimes": [{
            "name": "Documentation",
            "url": "https://docs.djangoproject.com/fr/5.1/",
            "icon": "fas fa-book",
            "permissions": ["auth.view_user"]
        }],
    },
    "footer": "<b>Gendarmerie Nationale</b> &copy; 2025 - Tous droits réservés.",
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = "/static/"
from pathlib import Path
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Utilisation du modèle utilisateur personnalisé
AUTH_USER_MODEL = "victimes.User"

# Configuration d'authentification
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Fichiers uploadés (actes de décès)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
